@{extends '../../templates/@layout.phtml'}


{block #menu}
<ul id="menu">
   <li{if $presenter->isCurrent('*:Subjects:*')} class="active"{/if}><a href="{link Subjects:}">Předměty</a></li>
   <li><a href="#" class="not-implemented">SZZ / BP / DP</a></li>
   <li><a href="#" class="not-implemented">Ostatní</a></li>
   <li><a href="{link logout}">Odhlásit</a></li>   
</ul>

<div id="submenu">
   {block #submenu}{/block}
</div>
{/block}